var target = 'iron-gym';

var moneyThresh = getServerMaxMoney(target) * 0.75;

var securityThresh = getServerMinSecurityLevel(target) + 5;

if (fileExists("level_2_hack.script", target)) {
	kill("level_2_hack.script", target);
}

brutessh(target);
nuke(target);

while (true) {
	if (getServerSecurityLevel(target) > securityThresh) {
		weaken(target);
	}
	else if (getServerMoneyAvailable(target) < moneyThresh) {
		grow(target);
	}
	else {
		hack(target);
	}
}